#!/bin/bash
clear
echo "Setting up toolchain for use"
cd libexec/gcc/x86_64-unknown-linux-gnu/5.3.0
echo "unziping cc1"
unzip cc1
echo "unziping cc1plus"
unzip cc1plus
echo "unziping lto1"
unzip lto1
echo "removing cc1.zip cc1plus.zip and lto1.zip"
rm cc1.zip cc1plus.zip lto1.zip
echo "all done"
echo " "
echo "set path to the toolchain and start compiling :) "
